# Generated by Django 2.2.4 on 2019-08-26 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersworks', '0002_auto_20190826_2111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='default.png', upload_to='profile_pics'),
        ),
    ]
