# Generated by Django 2.2.4 on 2019-09-03 07:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('eventcyrcle', '0004_auto_20190903_1458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ourevents',
            name='date_of_event',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
