# Generated by Django 2.2.4 on 2019-09-08 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventcyrcle', '0007_auto_20190908_1452'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='author2',
            field=models.CharField(default='<django.db.models.fields.related.ForeignKey>', max_length=100),
        ),
    ]
